import assert from "node:assert/strict";
import { spawn, spawnSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, readdir, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const enabled = process.env.SPORADES_REAL_CLAMAV_DEV === "1";
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function dockerDevNames() { const result = spawnSync("docker", ["ps", "-a", "--filter", "name=sporades-dev-clamav-", "--format", "{{.Names}}"], { encoding: "utf8", timeout: 30_000 }); assert.equal(result.status, 0, result.stderr); return new Set(result.stdout.trim().split("\n").filter(Boolean)); }
function waitLine(child) { return new Promise((resolve, reject) => { let pending = ""; let stdout = ""; let stderr = ""; const timer = setTimeout(() => reject(new Error(`Dev start timed out. ${stdout} ${stderr}`)), 180_000); child.stdout.on("data", (chunk) => { stdout = (stdout + chunk).slice(-8192); pending += chunk; const lines = pending.split("\n"); pending = lines.pop(); for (const line of lines) { try { const value = JSON.parse(line); if (value?.data?.event === "started") { clearTimeout(timer); resolve(value); return; } } catch {} } }); child.stderr.on("data", (chunk) => { stderr = (stderr + chunk).slice(-8192); }); child.once("exit", (code) => { clearTimeout(timer); reject(new Error(`Dev exited ${code}. ${stdout} ${stderr}`)); }); }); }
function stopChild(child) { return new Promise((resolve) => { if (child.exitCode !== null) return resolve(child.exitCode); child.once("exit", resolve); child.kill("SIGTERM"); }); }
async function linkedSession(url, suffix) { const html = await (await fetch(url)).text(); const token = /window\.__SPORADES_CONNECTION_TOKEN="([^"]+)"/.exec(html)?.[1]; assert(token); const target = new URL("/__sporades/ws", url); target.searchParams.set("connectionToken", token); const socket = new WebSocket(target); await new Promise((resolve, reject) => { socket.addEventListener("open", resolve, { once: true }); socket.addEventListener("error", reject, { once: true }); }); const id = `signup-${suffix}`; const result = new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error("Auth timed out")), 10_000); socket.addEventListener("message", (event) => { const message = JSON.parse(event.data); if (message.id === id) { clearTimeout(timer); resolve(message); } }); }); socket.send(JSON.stringify({ id, type: "auth.signUp", provider: "email", credentials: { email: `scanner-${suffix}@example.com`, password: "correct horse battery staple", name: "Scanner" } })); const signed = await result; socket.close(); assert.equal(signed.data.ok, true, JSON.stringify(signed)); return signed.data.sessionToken; }
async function scan(url, sessionToken, key, bytes) { const boundary = `acceptance-${key}`; const body = Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="evidence.txt"\r\nContent-Type: text/plain\r\n\r\n`), bytes, Buffer.from(`\r\n--${boundary}--`)]); const response = await fetch(`${url}/upload`, { method: "POST", headers: { "content-type": `multipart/form-data; boundary=${boundary}`, "idempotency-key": key, "x-sporades-session-token": sessionToken }, body }); const text = await response.text(); assert.equal(response.status, 200, text); return JSON.parse(text); }
async function waitHealthy(url) { let last; for (let attempt = 0; attempt < 60; attempt += 1) { last = await fetch(new URL("/__sporades/health/runtime", url), { headers: { "x-sporades-host-probe": "dev-clamav-acceptance" } }); if (last.status === 200) return; await new Promise((resolve) => setTimeout(resolve, 500)); } assert.equal(last?.status, 200, await last?.text()); }

test("normal sporades dev owns a Unix-only ClamAV sidecar and reuses signatures", { skip: !enabled }, async () => {
  const parent = await mkdtemp(path.join(tmpdir(), "sporades-real-dev-clamav-")); const project = path.join(parent, "inspection"); const before = dockerDevNames(); const beforeSockets = new Set((await readdir(tmpdir())).filter((name) => name.startsWith("sporades-dev-clamav-"))); let child;
  try {
    const created = spawnSync(process.execPath, [path.join(repoRoot, "bin", "sporades.js"), "create", "inspection", "--template", "blank", "--framework", "vanilla", "--toolchain", "esbuild", "--no-install", "--no-git", "--json"], { cwd: parent, encoding: "utf8", timeout: 30_000 }); assert.equal(created.status, 0, created.stderr);
    const projectConfigPath = path.join(project, "sporades.json"); const projectConfig = JSON.parse(await readFile(projectConfigPath, "utf8")); projectConfig.auth = { providers: { email: { enabled: true } } }; await writeFile(projectConfigPath, `${JSON.stringify(projectConfig, null, 2)}\n`);
    await mkdir(path.join(project, "node_modules"), { recursive: true }); await symlink(repoRoot, path.join(project, "node_modules", "sporades"));
    await writeFile(path.join(project, "server", "index.ts"), `import { capsule, endpoint } from "sporades/server";\nconst limits = { maxFiles: 1, maxFileBytes: 10485760, maxTotalFileBytes: 10485760, maxFieldCount: 1, maxFieldBytes: 1024, maxTotalFieldBytes: 1024, allowedPathPrefixes: ["/attachments"], requestKeyHeader: "idempotency-key", partKeyHeader: "content-id", requireStablePartKeys: false, inspection: { policyRevision: "dev-real-v1", requiredInspectors: ["clamav"] } };\nexport default capsule({ name: "inspection", endpoints: { upload: endpoint({ method: "POST", path: "/upload", body: { multipart: limits } }, async (ctx) => ({ status: 200, body: await ctx.files.inspection(ctx.request.multipart.files[0]) })) } });\n`);
    for (let restart = 0; restart < 2; restart += 1) {
      child = spawn(process.execPath, [path.join(repoRoot, "bin", "sporades.js"), "dev", "--json", "--port", "0"], { cwd: project, stdio: ["ignore", "pipe", "pipe"] }); const started = await waitLine(child); const url = started.data.url; const sessionToken = await linkedSession(url, restart);
      await waitHealthy(url);
      const clean = await scan(url, sessionToken, `clean-${restart}`, Buffer.from("clean support evidence")); assert.equal((clean.data?.verdicts ?? clean.verdicts)[0].outcome, "clean", JSON.stringify(clean));
      const infected = await scan(url, sessionToken, `eicar-${restart}`, Buffer.from("X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*")); assert.equal((infected.data?.verdicts ?? infected.verdicts)[0].outcome, "rejected", JSON.stringify(infected));
      const active = [...dockerDevNames()].filter((name) => !before.has(name)); assert.equal(active.length, 1); const inspect = spawnSync("docker", ["inspect", active[0]], { encoding: "utf8", timeout: 30_000 }); assert.equal(inspect.status, 0, inspect.stderr); const details = JSON.parse(inspect.stdout)[0]; assert.deepEqual(details.NetworkSettings.Ports, {}); assert.equal(String(details.Config.Cmd).includes("TCPSocket"), false);
      assert.equal(await stopChild(child), 0); child = undefined; assert.deepEqual([...dockerDevNames()].filter((name) => !before.has(name)), []); assert.deepEqual((await readdir(tmpdir())).filter((name) => name.startsWith("sporades-dev-clamav-") && !beforeSockets.has(name)), []);
    }
    const signatureFiles = await readdir(path.join(project, ".sporades", "clamav", "clamav")); assert.equal(signatureFiles.some((name) => /^daily\.(?:cld|cvd)$/.test(name)), true);
  } finally { if (child) await stopChild(child).catch(() => {}); for (const name of [...dockerDevNames()].filter((item) => !before.has(item))) spawnSync("docker", ["rm", "-f", name], { encoding: "utf8", timeout: 30_000 }); await rm(parent, { recursive: true, force: true }); }
});
