import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { test } from "node:test";
import { openDevDatabase } from "../dist/server-runtime-source.js";
import { job, mutation } from "../dist/server.js";
import { runMutation } from "../dist/server-runtime-source.js";
test("startup recovers an expired running lease as a consumed delayed retry", async()=>{const dir=await mkdtemp(path.join(tmpdir(),"sporades-lease-"));const file=path.join(dir,"data.db");let ran=0;let db=await openDevDatabase(file,"",{},{name:"jobs"},{jobs:{work:job(()=>{ran++;return null})}});try{const now=new Date().toISOString();db.sqlite.prepare("INSERT INTO sporades_auth_users (id,createdAt,displayName,email,picture,isAuthenticated,isGuest,provider) VALUES (?,?,?,?,?,?,?,?)").run("u",now,"u",null,null,0,1,"anonymous");db.sqlite.prepare("INSERT INTO sporades_jobs (id,handler,enqueuedByUserId,actorUserId,payload,status,availableAt,attempts,createdAt,retryJson,attemptHistory,leaseExpiresAt) VALUES (?,?,?,?,?,'running',?,1,?,?,?,?)").run("expired","work","u","u","{}",now,now,'{"maxAttempts":2,"delayMs":10}',"[]",new Date(Date.now()-1).toISOString());db.close();db=await openDevDatabase(file,"",{},{name:"jobs"},{jobs:{work:job(()=>{ran++;return null})}});assert.equal(db.sqlite.prepare("SELECT status FROM sporades_jobs WHERE id='expired'").get().status,"delayed");await new Promise(r=>setTimeout(r,30));assert.equal(ran,1);assert.equal(db.sqlite.prepare("SELECT attempts,status FROM sporades_jobs WHERE id='expired'").get().attempts,2);}finally{db.close();await rm(dir,{recursive:true,force:true});}});

test("expired exhausted leases fail safely and retained idempotency survives restart", async()=>{const dir=await mkdtemp(path.join(tmpdir(),"sporades-lease-exhausted-"));const file=path.join(dir,"data.db");let db=await openDevDatabase(file,"",{},{name:"jobs"},{jobs:{}});try{const now=new Date().toISOString();db.sqlite.prepare("INSERT INTO sporades_auth_users (id,createdAt,displayName,email,picture,isAuthenticated,isGuest,provider) VALUES (?,?,?,?,?,?,?,?)").run("u",now,"u",null,null,0,1,"anonymous");db.sqlite.prepare("INSERT INTO sporades_jobs (id,handler,enqueuedByUserId,actorUserId,payload,status,availableAt,attempts,createdAt,retryJson,attemptHistory,leaseExpiresAt,idempotencyKey) VALUES (?,?,?,?,?,'running',?,1,?,?,?,?,'once')").run("exhausted","missing","u","u","{}",now,now,'{"maxAttempts":1,"delayMs":0}',"[]",new Date(Date.now()-1).toISOString());db.close();db=await openDevDatabase(file,"",{},{name:"jobs"},{jobs:{}});const row=db.sqlite.prepare("SELECT status,failure FROM sporades_jobs WHERE id='exhausted'").get();assert.equal(row.status,"failed");assert.equal(JSON.parse(row.failure).code,"JOB_LEASE_EXPIRED");}finally{db.close();await rm(dir,{recursive:true,force:true});}});

test("retained idempotency resolves one Job after runtime restart",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"sporades-idempotency-restart-"));const file=path.join(dir,"data.db");const capsule={jobs:{noop:job(()=>null)},mutations:{enqueue:mutation(ctx=>ctx.jobs.enqueue("noop",{},{idempotencyKey:"same"}))}};let db=await openDevDatabase(file,"",{},{name:"jobs"},capsule);const auth={userId:"u",displayName:"u",email:null,picture:null,isAuthenticated:false,isGuest:true,provider:"anonymous"};try{db.sqlite.prepare("INSERT INTO sporades_auth_users (id,createdAt,displayName,email,picture,isAuthenticated,isGuest,provider) VALUES (?,?,?,?,?,?,?,?)").run("u",new Date().toISOString(),"u",null,null,0,1,"anonymous");const first=await runMutation(db,auth,"enqueue",[]);await new Promise(r=>setTimeout(r,10));db.close();db=await openDevDatabase(file,"",{},{name:"jobs"},capsule);const second=await runMutation(db,auth,"enqueue",[]);assert.equal(first.data.id,second.data.id);assert.equal(db.sqlite.prepare("SELECT count(*) AS count FROM sporades_jobs").get().count,1);await new Promise(r=>setTimeout(r,10));}finally{db.close();await rm(dir,{recursive:true,force:true});}});

test("conditional lease claim has one winner and expired side effects may run again",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"sporades-claim-race-"));const file=path.join(dir,"data.db");let effects=0;let db=await openDevDatabase(file,"",{},{name:"jobs"},{jobs:{work:job(()=>{effects++;return null})}});try{const now=new Date().toISOString();db.sqlite.prepare("INSERT INTO sporades_auth_users (id,createdAt,displayName,email,picture,isAuthenticated,isGuest,provider) VALUES (?,?,?,?,?,?,?,?)").run("u",now,"u",null,null,0,1,"anonymous");db.sqlite.prepare("INSERT INTO sporades_jobs (id,handler,enqueuedByUserId,actorUserId,payload,status,availableAt,attempts,createdAt,retryJson,attemptHistory) VALUES (?,?,?,?,?,'queued',?,0,?,?,?)").run("claim","work","u","u","{}",now,now,'{"maxAttempts":2,"delayMs":0}',"[]");const a=db.sqlite.prepare("UPDATE sporades_jobs SET status='running' WHERE id=? AND status='queued'").run("claim");const b=db.sqlite.prepare("UPDATE sporades_jobs SET status='running' WHERE id=? AND status='queued'").run("claim");assert.equal(a.changes+b.changes,1);db.sqlite.prepare("UPDATE sporades_jobs SET leaseExpiresAt=?, status='running', attempts=1 WHERE id=?").run(new Date(Date.now()-1).toISOString(),"claim");db.close();db=await openDevDatabase(file,"",{},{name:"jobs"},{jobs:{work:job(()=>{effects++;return null})}});await new Promise(r=>setTimeout(r,20));assert.equal(effects,1);}finally{db.close();await rm(dir,{recursive:true,force:true});}});

test("expired leases recover in availableAt then Job ID order",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"sporades-lease-order-"));const file=path.join(dir,"data.db");const seen=[];let db=await openDevDatabase(file,"",{},{name:"jobs"},{jobs:{work:job((ctx,p)=>seen.push(p.id))}});try{const now=new Date().toISOString();db.sqlite.prepare("INSERT INTO sporades_auth_users (id,createdAt,displayName,email,picture,isAuthenticated,isGuest,provider) VALUES (?,?,?,?,?,?,?,?)").run("u",now,"u",null,null,0,1,"anonymous");for(const id of ["b","a"])db.sqlite.prepare("INSERT INTO sporades_jobs (id,handler,enqueuedByUserId,actorUserId,payload,status,availableAt,attempts,createdAt,retryJson,attemptHistory,leaseExpiresAt) VALUES (?,?,?,?,?,'running',?,1,?,?,?,?)").run(id,"work","u","u",JSON.stringify({id}),now,now,'{"maxAttempts":2,"delayMs":0}',"[]",new Date(Date.now()-1).toISOString());db.close();db=await openDevDatabase(file,"",{},{name:"jobs"},{jobs:{work:job((ctx,p)=>seen.push(p.id))}});await new Promise(r=>setTimeout(r,25));assert.deepEqual(seen,["a","b"]);}finally{db.close();await rm(dir,{recursive:true,force:true});}});
