import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp, mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;

function command(bin, args, cwd, env = process.env) {
  env = { ...env, SPORADES_CONFIG_DIR: join(root, ".sporades/packed-stack-config") };
  return spawnSync(process.execPath, [bin, ...args], { cwd, env, encoding: 'utf8' });
}

test('packed CLI generates a stack outside checkout and preserves operator state', async () => {
  const temp = await mkdtemp(join(tmpdir(), 'sporades package '));
  const packed = spawnSync('npm', ['pack', '--json', '--ignore-scripts', '--pack-destination', temp], { cwd: root, encoding: 'utf8' });
  assert.equal(packed.status, 0, packed.stderr);
  const filename = JSON.parse(packed.stdout)[0].filename;
  const install = join(temp, 'installed package');
  await mkdir(install);
  const extracted = spawnSync('tar', ['-xzf', join(temp, filename), '-C', install], { encoding: 'utf8' });
  assert.equal(extracted.status, 0, extracted.stderr);
  const bin = join(install, 'package', 'bin', 'sporades.js');
  const legacy = join(temp, 'legacy stack');
  await mkdir(legacy);
  await writeFile(join(legacy, 'compose.yaml'), 'services:\n  old: {}\n');
  await writeFile(join(legacy, 'setup.mjs'), `import { writeFileSync } from 'node:fs'; writeFileSync(${JSON.stringify(join(legacy, 'untrusted-executed'))}, 'yes');\n`);
  const adopted = command(bin, ['monitoring', 'stack', 'init', '--dir', legacy, '--json'], temp);
  assert.equal(adopted.status, 0, adopted.stderr || adopted.stdout);
  assert.equal(JSON.parse(adopted.stdout).data.versionDifference.installed, 'unknown');
  await assert.rejects(readFile(join(legacy, 'stack-manifest.json'), 'utf8'), /ENOENT/);
  await assert.rejects(readFile(join(legacy, 'untrusted-executed'), 'utf8'), /ENOENT/);
  assert.match(await readFile(join(legacy, 'compose.yaml'), 'utf8'), /old/);
  assert.equal((await stat(join(legacy, '.private', 'credentials.json'))).mode & 0o777, 0o600);
  const target = join(temp, 'monitoring stack');
  const first = command(bin, ['monitoring', 'stack', 'init', '--dir', target, '--json'], temp);
  assert.equal(first.status, 0, first.stderr || first.stdout);
  const result = JSON.parse(first.stdout);
  assert.equal(result.ok, true);
  assert.equal(result.data.path, target);
  assert.deepEqual(result.data.missingAssets, []);
  const gatewaySource = await readFile(join(root, 'monitoring', 'trace', 'gateway.mjs'), 'utf8');
  assert.equal(await readFile(join(install, 'package', 'monitoring', 'trace', 'gateway.mjs'), 'utf8'), gatewaySource);
  assert.equal(await readFile(join(target, 'gateway.mjs'), 'utf8'), gatewaySource);
  for (const name of ['smoke.mjs', 'README.md', 'inventory-contract.mjs', 'inventory-store.mjs', 'inventory.mjs', 'sender-credentials.mjs', 'pipeline-dashboard.json', 'pipeline-rules.yaml', 'collector-persistent.yaml', 'compose.queue.yaml', 'OUTAGES.md', 'MAINTENANCE.md']) {
    const source = await readFile(join(root, 'monitoring', 'trace', name), 'utf8');
    assert.equal(await readFile(join(install, 'package', 'monitoring', 'trace', name), 'utf8'), source);
    assert.equal(await readFile(join(target, name), 'utf8'), source);
  }
  const sender = command(bin, ['monitoring', 'sender', 'issue', '--dir', target, '--sender', 'packed-host', '--host', 'packed.example', '--json'], temp);
  assert.equal(sender.status, 0, sender.stdout + sender.stderr);
  assert.equal(JSON.parse(sender.stdout).data.senders[0].generation, 1);
  const handoff = join(temp, 'packed-handoff.env');
  const exported = command(bin, ['monitoring', 'sender', 'export', '--dir', target, '--sender', 'packed-host', '--out', handoff, '--json'], temp);
  assert.equal(exported.status, 0, exported.stdout + exported.stderr);
  const token = (await readFile(handoff, 'utf8')).match(/TRACE_INGEST_TOKEN=([^\n]+)/)[1];
  assert(!(sender.stdout + exported.stdout).includes(token));
  assert.equal((await stat(handoff)).mode & 0o777, 0o600);
  assert.match(await readFile(join(target, 'compose.yaml'), 'utf8'), /prom\/prometheus:v3\.13\.3[\s\S]*grafana\/grafana:13\.2\.2/);
  assert.match(await readFile(join(target, 'compose.yaml'), 'utf8'), /\.\/pipeline-rules\.yaml:\/etc\/prometheus\/pipeline-rules\.yaml:ro/);
  assert.match(await readFile(join(target, 'prometheus.yaml'), 'utf8'), /rule_files:\s*\n\s*- \/etc\/prometheus\/pipeline-rules\.yaml/);
  const api = JSON.parse(await readFile(join(target, 'api-dashboard.json'), 'utf8'));
  assert.equal(api.title, 'Sporades Capsule API');
  assert.equal(api.templating.list.find(variable => variable.name === 'metric_window')?.current.value, '12m');
  assert(api.panels.filter(panel => panel.targets.some(target => /rate\(/.test(target.expr))).every(panel => panel.targets.every(target => target.expr.includes('[${metric_window}]'))));
  const resources = JSON.parse(await readFile(join(target, 'resource-dashboard.json'), 'utf8'));
  assert.equal(resources.uid, 'sporades-resources');
  assert.match(resources.panels.find(panel => panel.title === 'CPU cores used')?.targets[0].expr ?? '', /rate\(process_cpu_time_seconds_total.*instance=~/);
  assert.equal(resources.panels.find(panel => panel.title === 'JavaScript heap')?.targets.length, 2);
  assert(resources.panels.some(panel => panel.title === 'V8 heap limit'));
  assert.match(resources.panels.find(panel => panel.title === 'GC collections per second')?.targets[0].expr ?? '', /rate\(process_gc_count_total.*instance=~/);
  assert.match(resources.panels.find(panel => panel.title === 'GC pause time per second')?.targets[0].expr ?? '', /rate\(process_gc_duration_seconds_total.*instance=~/);
  assert.equal(resources.templating.list.find(variable => variable.name === 'metric_window')?.current.value, '12m');
  assert.match(resources.panels.find(panel => panel.title === 'Event-loop delay')?.targets[0].expr ?? '', /max_over_time\(process_event_loop_delay_max_milliseconds.*\[\$\{metric_window\}\]\)/);
  assert.match(resources.panels.find(panel => panel.title === 'Event-loop utilization')?.targets[0].expr ?? '', /process_event_loop_utilization_ratio.*instance=~/);
  assert.match(resources.panels.find(panel => panel.title === 'API request p95 latency')?.targets[0].expr ?? '', /http_server_request_duration_seconds_bucket.*instance=~/);

  const copiedExample = join(temp, 'copied example stack');
  await mkdir(copiedExample);
  await writeFile(join(copiedExample, '.env'), await readFile(join(install, 'package', 'monitoring', 'trace', '.env.example'), 'utf8'));
  const copiedInit = command(bin, ['monitoring', 'stack', 'init', '--dir', copiedExample, '--json'], temp);
  assert.equal(copiedInit.status, 0, copiedInit.stderr || copiedInit.stdout);
  assert.doesNotMatch(await readFile(join(copiedExample, '.private', 'credentials.json'), 'utf8'), /REPLACE_WITH_GENERATED_SECRET/);
  assert.equal(command(bin, ['monitoring', 'stack', 'validate', '--dir', copiedExample, '--json'], temp).status, 0);

  const placeholder = join(temp, 'placeholder stack');
  await mkdir(placeholder);
  await writeFile(join(placeholder, '.env'), 'TRACE_TLS_MODE=proxy\nTRACE_UI_PASSWORD=REPLACE_WITH_GENERATED_SECRET\n');
  const rejectedInit = command(bin, ['monitoring', 'stack', 'init', '--dir', placeholder, '--json'], temp);
  assert.equal(rejectedInit.status, 1);
  assert.match(rejectedInit.stdout, /TRACE_UI_PASSWORD/);
  assert.doesNotMatch(rejectedInit.stdout + rejectedInit.stderr, /REPLACE_WITH_GENERATED_SECRET/);
  await assert.rejects(stat(join(placeholder, '.private', 'credentials.json')), /ENOENT/);
  const rejectedValidate = command(bin, ['monitoring', 'stack', 'validate', '--dir', placeholder, '--json'], temp);
  assert.equal(rejectedValidate.status, 1);
  assert.match(rejectedValidate.stdout, /TRACE_UI_PASSWORD/);

  assert.equal((await stat(join(target, '.private', 'grafana-admin-password'))).mode & 0o777, 0o600);
  assert.ok(result.data.missing.includes('TRACE_CERT_FILE'));
  const environment = join(target, '.env');
  const before = await readFile(environment, 'utf8');
  const custom = `${before}OPERATOR_EXTRA=keep:$VALUE # literal\n`;
  await writeFile(environment, custom.replace(/TRACE_INGEST_TOKEN=[^\n]*/, 'TRACE_INGEST_TOKEN=chosen:$VALUE # literal'));
  await writeFile(join(target, 'compose.override.yaml'), 'services: {}\n');
  await writeFile(join(target, 'compose.yaml'), `${await readFile(join(target, 'compose.yaml'), 'utf8')}\n# operator override\n`);
  await mkdir(join(target, 'data'));
  await writeFile(join(target, 'data', 'keep'), 'history');
  const second = command(bin, ['monitoring', 'stack', 'init', '--dir', target, '--json'], temp);
  assert.equal(second.status, 0, second.stderr || second.stdout);
  assert.match(await readFile(environment, 'utf8'), /OPERATOR_EXTRA=keep:\$VALUE # literal/);
  assert.match(await readFile(environment, 'utf8'), /TRACE_INGEST_TOKEN=chosen:\$VALUE # literal/);
  assert.equal((await readFile(join(target, 'data', 'keep'), 'utf8')), 'history');
  assert.equal((await readFile(join(target, 'compose.override.yaml'), 'utf8')), 'services: {}\n');
  assert.match(await readFile(join(target, 'compose.yaml'), 'utf8'), /# operator override/);
  assert.equal(JSON.parse(await readFile(join(target, '.private', 'credentials.json'), 'utf8')).ingestToken, 'chosen:$VALUE # literal');
  assert.equal((await stat(environment)).mode & 0o777, 0o600);
  assert.equal((await stat(join(target, '.private', 'credentials.json'))).mode & 0o777, 0o600);
  const validation = command(bin, ['monitoring', 'stack', 'validate', '--dir', target, '--json'], temp);
  assert.equal(validation.status, 0, validation.stderr || validation.stdout);
  assert.deepEqual(JSON.parse(validation.stdout).data.missing, ['TRACE_CERT_FILE', 'TRACE_KEY_FILE']);
  assert.ok(JSON.parse(validation.stdout).data.overrides.includes('compose.yaml'));
  const directSetup = command(join(target, 'setup.mjs'), [], target);
  assert.equal(directSetup.status, 1);
  assert.match(directSetup.stderr, /TRACE_CERT_FILE, TRACE_KEY_FILE/);
  const manifestPath = join(target, 'stack-manifest.json');
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  await writeFile(manifestPath, JSON.stringify({ ...manifest, packageVersion: '0.0.0' }));
  const different = command(bin, ['monitoring', 'stack', 'validate', '--dir', target, '--json'], temp);
  assert.equal(different.status, 0, different.stderr || different.stdout);
  assert.equal(JSON.parse(different.stdout).data.versionDifference.installed, '0.0.0');
  const unavailable = command(bin, ['monitoring', 'stack', 'validate', '--dir', target, '--json'], temp, { ...process.env, PATH: temp });
  assert.equal(unavailable.status, 1);
  assert.match(JSON.parse(unavailable.stdout).error.hint, /Docker Compose 2\.40\.3/);
  const fakeDocker = join(temp, 'fake docker');
  await mkdir(fakeDocker);
  await writeFile(join(fakeDocker, 'docker'), '#!/bin/sh\nif [ "$1" = "compose" ]; then echo 5.5.1; else echo 28.5.0; fi\n', { mode: 0o755 });
  const oldEngine = command(bin, ['monitoring', 'stack', 'validate', '--dir', target, '--json'], temp, { ...process.env, PATH: fakeDocker });
  assert.equal(oldEngine.status, 1);
  assert.match(JSON.parse(oldEngine.stdout).error.hint, /Docker Engine 29/);
  assert.doesNotMatch(`${first.stdout}${second.stdout}${validation.stdout}`, /chosen|\$VALUE/);
});
