import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { once } from 'node:events';
import { createGateway, createGatewayMetrics } from '../monitoring/trace/gateway.mjs';

test('gateway bounds stalled ingestion, reports pressure privately and automatically resumes', { timeout: 12_000 }, async t => {
  let stall = true;
  let waiting = 0;
  const backend = createServer(async (req, res) => { for await (const _part of req) {} waiting++; if (!stall) res.end('{}'); }).listen(0, '127.0.0.1');
  await once(backend, 'listening');
  const gateway = createGateway({ ingestToken: 'private-token', uiUser: 'viewer', uiPassword: 'private-password', collectorUrl: `http://127.0.0.1:${backend.address().port}`, jaegerUrl: 'http://127.0.0.1:1' }).listen(0, '127.0.0.1');
  await once(gateway, 'listening');
  const metrics = createGatewayMetrics(gateway).listen(0, '127.0.0.1');
  await once(metrics, 'listening');
  t.after(async () => { for (const server of [gateway, metrics, backend]) { server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); } });
  const origin = `http://127.0.0.1:${gateway.address().port}`;
  const metricUrl = `http://127.0.0.1:${metrics.address().port}/metrics`;
  const send = () => fetch(`${origin}/v1/traces`, { method: 'POST', headers: { authorization: 'Bearer private-token', 'content-type': 'application/json' }, body: '{}' });
  const active = Array.from({ length: 32 }, send);
  const deadline = Date.now() + 1000;
  while (waiting < 32 && Date.now() < deadline) await new Promise(resolve => setTimeout(resolve, 10));
  assert.equal(waiting, 32);
  const at = performance.now();
  assert.equal((await send()).status, 503);
  assert(performance.now() - at < 500, 'overflow does not wait for a backend');
  const saturated = await (await fetch(metricUrl)).text();
  assert.match(saturated, /sporades_gateway_ingest_in_flight 32/);
  assert.match(saturated, /sporades_gateway_ingest_capacity 32/);
  assert.match(saturated, /sporades_gateway_ingest_rejected_total 1/);
  assert.doesNotMatch(saturated, /last_success|private-token|private-password/);
  assert.equal((await fetch(`${origin}/metrics`)).status, 401, 'scrape endpoint is not publicly exposed');
  assert((await Promise.all(active)).every(response => response.status === 503));
  stall = false;
  assert.equal((await send()).status, 200);
  const recovered = await (await fetch(metricUrl)).text();
  assert.match(recovered, /sporades_gateway_ingest_in_flight 0/);
  assert.match(recovered, /sporades_gateway_ingest_failures_total 32/);
  assert.match(recovered, /sporades_gateway_ingest_last_success_seconds [1-9]/);
});
