import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const entries = [
  {
    entryPoint: path.join(repoRoot, "src", "cli", "sporades.ts"),
    outfile: path.join(repoRoot, "bin", "sporades.js"),
  },
  {
    entryPoint: path.join(repoRoot, "src", "cli", "sporades-host-helper.ts"),
    outfile: path.join(repoRoot, "bin", "sporades-host-helper.js"),
  },
];

await mkdir(path.join(repoRoot, "bin"), { recursive: true });

await Promise.all(
  entries.map(async ({ entryPoint, outfile }) => {
    await build({
      entryPoints: [entryPoint],
      outfile,
      bundle: true,
      platform: "node",
      format: "esm",
      target: "node22",
      external: ["esbuild", "vite"],
      sourcemap: false,
      logLevel: "info",
      banner: {
        js: "// Generated by `npm run build` from TypeScript sources. Do not edit by hand.\nimport { createRequire as __sporadesCreateRequire } from 'node:module'; const require = __sporadesCreateRequire(import.meta.url);",
      },
    });
    const generated = await readFile(outfile, "utf8");
    await writeFile(outfile, generated.replace(/[ \t]+(?=\n)/g, ""));
    await chmod(outfile, 0o755);
  }),
);

// Ship exactly the same inventory validation contract to the monitoring gateway.
const inventoryContract = await readFile(path.join(repoRoot, "dist", "cli", "inventory-contract.js"), "utf8");
await writeFile(path.join(repoRoot, "monitoring", "trace", "inventory-contract.mjs"), inventoryContract.replace(/\n\/\/# sourceMappingURL=.*$/, "\n"));
